### PR TITLE
Fix scan exception when the start key is empty

### LINKED ISSUE #187: [BUG] raw kv scan cannot start with empty start key
**Describe the bug**

In ScanIterator.java, the start key cannot be empty.
```java
if (startKey.isEmpty()) {
  throw new IllegalArgumentException("start key cannot be empty");
} 
```
thus if RawKV wants to scan from the very beginning of all data, the ScanIterator will throw an exception.

**Java Client and TiDB/TiKV version info**

master

### PR DESCRIPTION
**Pull request by birdstorm**
Signed-off-by: birdstorm <samuelwyf@hotmail.com>

### What problem does this PR solve? 
Close #187 

### What is changed and how it works?
Change the check condition for the scan operations to allow empty start key.

### Check List 

Tests 

 - Unit test
 - Integration test

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### CODE REVIEW

File: src/main/java/org/tikv/common/operation/iterator/ScanIterator.java [hunk 1]
```diff
@@ -107,7 +104,7 @@ boolean cacheLoadFails() {
         startKey = lastKey.next().toByteString();
       }
       // notify last batch if lastKey is greater than or equal to endKey
-      if (hasEndKey && lastKey.compareTo(endKey) >= 0) {
+      if (hasEndKey && lastKey.compareTo(endKey) >= 0 || startKey.isEmpty()) {
         processingLastBatch = true;
         startKey = null;
       }
```
Comment (marsishandsome) [inline src/main/java/org/tikv/common/operation/iterator/ScanIterator.java:110]:
```suggestion
      if(startKey.isEmpty()) {
          processingLastBatch = true;
      }
      
      if (hasEndKey && lastKey.compareTo(endKey) >= 0) {
        processingLastBatch = true;
        startKey = null;
      }
```

File: src/main/java/org/tikv/common/operation/iterator/ScanIterator.java [hunk 2]
```diff
@@ -107,7 +104,7 @@ boolean cacheLoadFails() {
         startKey = lastKey.next().toByteString();
       }
       // notify last batch if lastKey is greater than or equal to endKey
-      if (hasEndKey && lastKey.compareTo(endKey) >= 0) {
+      if (hasEndKey && lastKey.compareTo(endKey) >= 0 || startKey.isEmpty()) {
```
Comment (marsishandsome) [inline src/main/java/org/tikv/common/operation/iterator/ScanIterator.java:107]: `startKey.isEmpty()` always equals false

Comment (birdstorm) [reply src/main/java/org/tikv/common/operation/iterator/ScanIterator.java:107]: it is possible that startKey is ByteString.EMPTY, which indicates +♾

Comment (marsishandsome) [reply src/main/java/org/tikv/common/operation/iterator/ScanIterator.java:107]: ok, please update the comment

**Review by marsishandsome — APPROVED** [review]
LGTM

File: src/main/java/org/tikv/common/operation/iterator/ScanIterator.java (hunk 2 above)
Comment (birdstorm) [reply src/main/java/org/tikv/common/operation/iterator/ScanIterator.java:108]: @marsishandsome done

**Review by Little-Wallace — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
