### PR TITLE
[close #540] rawkv: fix scan return empty set while exist empty key

### LINKED ISSUE #540: rawkv: scan return 0 kv pair while exist key ByteString.EMPTY
### 1. Describe the bug

`rawScan` interface will return 0 KV-pair while there is an empty key inserted. It could be introduced by the warmup phase of `client-java`.

### 2. Minimal reproduce step (Required)
```java
client.put(ByteString.EMPTY, ByteString.EMPTY);
System.out.println(client.scan(ByteString.EMPTY, 2).size());
```

### 3. What did you see instead (Required)

Output 1

### 4. What did you expect to see? (Required)

Output 0

### 5. What are your Java Client and TiKV versions? (Required)

- Client Java: master
- TiKV: v5.0.3

### PR DESCRIPTION
**Pull request by iosmanthus**
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>

### What problem does this PR solve?

Issue Number: close #540

Problem Description:

This pull request adds an empty key check for `RawScanIterator.hasNext`, otherwise, if there is an empty key in TiKV, the scan will always return an empty set.

### Check List for Tests

This PR has been tested by at least one of the following methods:
- Integration test

### CODE REVIEW

File: src/main/java/org/tikv/common/operation/iterator/RawScanIterator.java [hunk 1]
```diff
@@ -67,11 +68,18 @@ TiRegion loadCurrentRegionToCache() throws GrpcException {
     }
   }
 
-  private boolean notEndOfScan() {
-    return limit > 0
-        && !(processingLastBatch
-            && (index >= currentCache.size()
-                || Key.toRawKey(currentCache.get(index).getKey()).compareTo(endKey) >= 0));
+  private boolean eof() {
```
Comment (zz-jason) [inline src/main/java/org/tikv/common/operation/iterator/RawScanIterator.java:71]: usually, `eof` is short for `end of file`, how about renaming it to `endOfScan()` to eliminate misunderstanding?

**Comment by zz-jason** [comment]
test failed, please take a look:
```
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    RawKVClientTest.scanTestForIssue540:385 expected:<1> but was:<2>
[INFO] 
Error:  Tests run: 77, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by iosmanthus** [comment]
> test failed, please take a look:
> 
> ```
> [INFO] Results:
> [INFO] 
> Error:  Failures: 
> Error:    RawKVClientTest.scanTestForIssue540:385 expected:<1> but was:<2>
> [INFO] 
> Error:  Tests run: 77, Failures: 1, Errors: 0, Skipped: 0
> ```

Fixed, PTAL

File: src/main/java/org/tikv/common/operation/iterator/RawScanIterator.java (hunk 1 above)
Comment (iosmanthus) [reply src/main/java/org/tikv/common/operation/iterator/RawScanIterator.java]: Done.

File: src/main/java/org/tikv/common/operation/iterator/RawScanIterator.java [hunk 2]
```diff
@@ -67,11 +68,18 @@ TiRegion loadCurrentRegionToCache() throws GrpcException {
...
-        && !(processingLastBatch
-            && (index >= currentCache.size()
-                || Key.toRawKey(currentCache.get(index).getKey()).compareTo(endKey) >= 0));
+  private boolean endOfScan() {
+    if (limit <= 0) {
+      return true;
+    }
+    if (!processingLastBatch) {
+      return false;
+    }
```
[the remark this answers is not in the document]
Comment (iosmanthus) [reply src/main/java/org/tikv/common/operation/iterator/RawScanIterator.java:77]: In `hasNext`, it call `!endOfScan()` instead of `notEndOfScan` which is more confusing.

[the remark this answers is not in the document]
Comment (marsishandsome) [reply src/main/java/org/tikv/common/operation/iterator/RawScanIterator.java:77]: ok, I understand.
I recommend to separate `bug fix` and `code refactor` in 2 PRs.

File: src/test/java/org/tikv/raw/RawKVClientTest.java [hunk 3]
```diff
@@ -360,6 +378,16 @@ public void simpleTest() {
     return client.scan(RAW_START_KEY, RAW_END_KEY);
   }
 
+  // https://github.com/tikv/client-java/issues/540
```
Comment (marsishandsome) [inline src/test/java/org/tikv/raw/RawKVClientTest.java:381]: we can find the issue link according to the commit id.

**Review by marsishandsome — APPROVED** [review]
others, LGTM

File: src/main/java/org/tikv/common/operation/iterator/RawScanIterator.java [hunk 4]
```diff
@@ -67,11 +68,18 @@ TiRegion loadCurrentRegionToCache() throws GrpcException {
...
+    if (index >= currentCache.size()) {
+      return true;
```
Comment (zz-jason) [inline src/main/java/org/tikv/common/operation/iterator/RawScanIterator.java:79]: could you add some tests to cover the reported uncovered lines?

Comment (iosmanthus) [reply src/main/java/org/tikv/common/operation/iterator/RawScanIterator.java]: Delete these branches cause they will never be true.

**Review by zz-jason — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by zz-jason** [comment]
@iosmanthus test failed:
```
Error:  Errors: 
Error:    RawKVIngestTest.rawKVIngestTestWithTTL:113 » Grpc io.grpc.StatusRuntimeExcepti...
Error:    CASTest.rawPutIfAbsentTest:89 » Grpc retry is exhausted.
Error:    RawKVClientTest.getKeyTTLTest:142 » Grpc retry is exhausted.
[INFO] 
Error:  Tests run: 77, Failures: 0, Errors: 3, Skipped: 0
```

**Comment by iosmanthus** [comment]
> @iosmanthus test failed:
> 
> ```
> Error:  Errors: 
> Error:    RawKVIngestTest.rawKVIngestTestWithTTL:113 » Grpc io.grpc.StatusRuntimeExcepti...
> Error:    CASTest.rawPutIfAbsentTest:89 » Grpc retry is exhausted.
> Error:    RawKVClientTest.getKeyTTLTest:142 » Grpc retry is exhausted.
> [INFO] 
> Error:  Tests run: 77, Failures: 0, Errors: 3, Skipped: 0
> ```


It should be an upstream issues.
```
2022-02-28T14:02:09.8501660Z io.grpc.StatusRuntimeException: UNKNOWN: TTLNotEnabled
2022-02-28T14:02:09.8502057Z 	at io.grpc.Status.asRuntimeException(Status.java:535)
2022-02-28T14:02:09.8502573Z 	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:506)
2022-02-28T14:02:09.8503138Z 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:577)
2022-02-28T14:02:09.8503797Z 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
2022-02-28T14:02:09.8504371Z 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:786)
2022-02-28T14:02:09.8505069Z 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:764)
2022-02-28T14:02:09.8505618Z 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
2022-02-28T14:02:09.8506101Z 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
2022-02-28T14:02:09.8506658Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2022-02-28T14:02:09.8507232Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2022-02-28T14:02:09.8507651Z 	at java.lang.Thread.run(Thread.java:748)
2022-02-28T14:02:09.8508408Z [ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 218.773 s <<< FAILURE! - in org.tikv.common.importer.RawKVIngestTest
2022-02-28T14:02:09.8509060Z [ERROR] org.tikv.common.importer.RawKVIngestTest.rawKVIngestTestWithTTL  Time elapsed: 123.311 s  <<< ERROR!
2022-02-28T14:02:09.8509707Z org.tikv.common.exception.GrpcException: io.grpc.StatusRuntimeException: UNKNOWN: TTLNotEnabled
2022-02-28T14:02:09.8510348Z 	at org.tikv.common.importer.RawKVIngestTest.rawKVIngestTestWithTTL(RawKVIngestTest.java:113)
2022-02-28T14:02:09.8512194Z Caused by: io.grpc.StatusRuntimeException: UNKNOWN: TTLNotEnabled
```
