### PR TITLE
[close #433] fix calling getStoreById without backoffer

### LINKED ISSUE #433: Timeout in seekLeaderStore is not limited
Here is a SlogLog generated by the case `kill az with pd leader`.

```
{"start":"21:12:36.806","end":"21:12:42.299","duration":"5493ms","error":"retry is exhausted.","func":"get","region":"{Region[12358] ConfVer[547] Version[20] Store[20] KeyRange[indexInfo_:_pf01_:_APD01_:_3500770017512150000]:[indexInfo_:_pf01_:_APD01_:_3501970010589630000]}","key":"indexInfo_:_pf01_:_APD01_:_3501910019979570000","spans":[{"name":"getRegionByKey","start":"21:12:36.806","end":"21:12:36.806","duration":"0ms"},{"name":"callWithRetry tikvpb.Tikv/RawGet","start":"21:12:36.806","end":"21:12:42.298","duration":"5492ms"},{"name":"gRPC tikvpb.Tikv/RawGet","start":"21:12:36.806","end":"21:12:36.956","duration":"150ms"},{"name":"backoff BoCheckTimeout","start":"21:12:36.956","end":"21:12:36.956","duration":"0ms"},{"name":"backoff BoCheckTimeout","start":"21:12:36.956","end":"21:12:36.956","duration":"0ms"},{"name":"seekLeaderStore","start":"21:12:36.956","end":"21:12:42.298","duration":"5342ms"},{"name":"backoff BoRegionMiss","start":"21:12:42.298","end":"N/A","duration":"N/A"}]}
```

Timeout in seekLeaderStore is not limited
```
{
            "name":"seekLeaderStore",
            "start":"21:12:36.956",
            "end":"21:12:42.298",
            "duration":"5342ms"
        }
```

### PR DESCRIPTION
**Pull request by marsishandsome**
close #433

Timeout in seekLeaderStore is not limited.

We should use `backoffer` for all the gRPC calls.

### CODE REVIEW

**Review by birdstorm — APPROVED** [review]
LGTM

File: src/main/java/org/tikv/common/TiSession.java [hunk 1]
```diff
@@ -159,23 +159,46 @@ private static VersionInfo getVersionInfo() {
 
   private synchronized void warmUp() {
     long warmUpStartTime = System.currentTimeMillis();
+    warmUpStore();
+    warmUpRegion();
+    warmUpGrpc();
+    logger.info(
+        String.format("warm up duration %d ms", System.currentTimeMillis() - warmUpStartTime));
```
Comment (zz-jason) [inline src/main/java/org/tikv/common/TiSession.java:166]: should we use `System.nanoTime()` to avoid issues #404 happen again?

File: src/main/java/org/tikv/common/TiSession.java [hunk 2]
```diff
@@ -159,23 +159,46 @@ private static VersionInfo getVersionInfo() {
...
       for (Metapb.Store store : stores) {
         this.regionManager.updateStore(
-            null,
-            new TiStore(this.client.getStore(ConcreteBackOffer.newGetBackOff(), store.getId())));
+            null, new TiStore(this.client.getStore(backOffer, store.getId())));
       }
-      ByteString startKey = ByteString.EMPTY;
+    } catch (Exception e) {
+      // ignore error
+      logger.info("warm up store fails, ignored ", e);
```
Comment (zz-jason) [inline src/main/java/org/tikv/common/TiSession.java:182]: since the log is printed, it's better to print the failure reason from the exception to help to locate potential issues. warmup failures can be ignored by users, but cannot be ignored by us.

File: src/main/java/org/tikv/common/TiSession.java [hunk 3]
```diff
@@ -159,23 +159,46 @@ private static VersionInfo getVersionInfo() {
 
   private synchronized void warmUp() {
     long warmUpStartTime = System.currentTimeMillis();
+    warmUpStore();
```
Comment (zz-jason) [inline src/main/java/org/tikv/common/TiSession.java:162]: would it be better to handle exceptions in this function since all the exceptions are ignored? for example:

```java
try {
  warmUpStore();
  warmUpRegion();
  ...
} catch () {
  ...
}
```

File: src/main/java/org/tikv/common/util/ConcreteBackOffer.java [hunk 4]
```diff
@@ -185,6 +184,7 @@ public boolean canRetryAfterSleep(BackOffFunction.BackOffFuncType funcType, long
       }
     }
 
+    SlowLogSpan slowLogSpan = getSlowLog().start("backoff " + funcType.name());
```
Comment (zz-jason) [inline src/main/java/org/tikv/common/util/ConcreteBackOffer.java:187]: why move it here? should `BACKOFF_DURATION` also be moved?

**Review by zz-jason — COMMENTED** [review]
please add some tests.

File: src/main/java/org/tikv/common/TiSession.java (hunk 1 above)
Comment (marsishandsome) [reply src/main/java/org/tikv/common/TiSession.java:166]: we do not need an accurate measure here.

File: src/main/java/org/tikv/common/TiSession.java (hunk 2 above)
Comment (marsishandsome) [reply src/main/java/org/tikv/common/TiSession.java:182]: the current code will print the `e` in log file.

File: src/main/java/org/tikv/common/TiSession.java (hunk 3 above)
Comment (marsishandsome) [reply src/main/java/org/tikv/common/TiSession.java:162]: if `warmUpStore` failes, `warmUpRegion` will still run.

File: src/main/java/org/tikv/common/util/ConcreteBackOffer.java (hunk 4 above)
Comment (marsishandsome) [reply src/main/java/org/tikv/common/util/ConcreteBackOffer.java:187]: there is a `return` in line 184, which will cause ` "end":"N/A",`.
it's hard to understand it.

File: src/main/java/org/tikv/common/TiSession.java (hunk 1 above)
Comment (zz-jason) [reply src/main/java/org/tikv/common/TiSession.java:166]: since you are logging the time, and System.currentTimeMillis() can be misleading, I think we should avoid using it to record time durations.

File: src/main/java/org/tikv/common/util/ConcreteBackOffer.java (hunk 4 above)
Comment (zz-jason) [reply src/main/java/org/tikv/common/util/ConcreteBackOffer.java:187]: got. then why not move `BACKOFF_DURATION` to here as well?

File: src/main/java/org/tikv/common/TiSession.java (hunk 3 above)
Comment (zz-jason) [reply src/main/java/org/tikv/common/TiSession.java:162]: ok

File: src/main/java/org/tikv/common/util/ConcreteBackOffer.java (hunk 4 above)
Comment (marsishandsome) [reply src/main/java/org/tikv/common/util/ConcreteBackOffer.java:187]: good idea

**Review by zz-jason — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

File: src/main/java/org/tikv/common/util/ConcreteBackOffer.java (hunk 4 above)
Comment (iosmanthus) [reply src/main/java/org/tikv/common/util/ConcreteBackOffer.java:187]: Moving these lines to here might cause we can't see the backoff in slow log.

Comment (iosmanthus) [reply src/main/java/org/tikv/common/util/ConcreteBackOffer.java:187]: We may end this span while returning though we will see this backoff end shortly but this span is still there.

**Comment by iosmanthus** [comment]
Rest LGTM
