### PR TITLE
[close #596] fix tls reloading encouter slow thread npe

### LINKED ISSUE #596: TLS reloading encounter NPE while testing with multithread
### 1. Describe the bug

TLS reloading will produce NPE while `getChannel` with multiple threads.

### 2. Minimal reproduce step (Required)

```java
    // Test getChannel concurrently
    factory = new ChannelFactory(v, v, v, v, caPath, clientCertPath, clientKeyPath);

    List<Thread> tasks = new ArrayList<>(8);
    for (int i = 0; i < 8; i++) {
      ChannelFactory finalFactory = factory;
      Thread t = new Thread(() -> finalFactory.getChannel("127.0.0.1:2379", mapping));
      t.start();
      tasks.add(t);
    }

    for (Thread t : tasks) {
      t.join();
    }
```

### 3. What did you see instead (Required)
Panic

### 4. What did you expect to see? (Required)

Test pass

### 5. What are your Java Client and TiKV versions? (Required)

- Client Java: https://github.com/tikv/client-java/commit/7a123a07e2c8d2498610e10dda4de9c537bcc3cc

### PR DESCRIPTION
**Pull request by iosmanthus**
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>

### What problem does this PR solve?

Issue Number: close #596

Problem Description:

`getChannel` will encounter NPE for the slow thread might meet a null if the cert is unmodified.

### What is changed and how does it work?

Add an initial state for `SslContextBuilder`

### Check List for Tests

This PR has been tested by at least one of the following methods:
- Unit test

### Related changes

- Need to cherry-pick the release branch
- Need to update the documentation

### CODE REVIEW

File: src/main/java/org/tikv/common/util/ChannelFactory.java [hunk 1]
```diff
@@ -213,14 +214,15 @@ public ChannelFactory(
     this.keepaliveTimeout = keepaliveTimeout;
     this.idleTimeout = idleTimeout;
     this.certContext = new JksContext(jksKeyPath, jksKeyPassword, jksTrustPath, jksTrustPassword);
+    reloadSslContext();
   }
 
   @VisibleForTesting
   public boolean reloadSslContext() {
     if (certContext != null) {
       SslContextBuilder newBuilder = certContext.reload();
```
Comment (sunxiaoguang) [inline src/main/java/org/tikv/common/util/ChannelFactory.java:223]: There is still race between `isModified` check and rest of initialization code.

Comment (sunxiaoguang) [inline src/main/java/org/tikv/common/util/ChannelFactory.java:223]: There is still a race between `isModified` check and the rest of initialization logic.

Comment (sunxiaoguang) [reply src/main/java/org/tikv/common/util/ChannelFactory.java:223]: Reload in constructor can help mitigating NPE. But the race can make later certificate reload not working as expected.

**Comment by iosmanthus** [comment]
@sunxiaoguang PTAL

**Review by zhangyangyu — COMMENTED** [review]
Currently, all concurrency control applies to "getting the latest SSLContext builder"  and then "use it to initialize the connection pool correctly". But what if there are two consecutive cert change happening very quickly? Then we might use two different SSLContext builder to initialize the pool since when the second `reload` calls `connpool.clear`, the first call to `getChannel` migth stil not start initialize the pool.

**Comment by iosmanthus** [comment]
> Currently, all concurrency control applies to "getting the latest SSLContext builder" and then "use it to initialize the connection pool correctly". But what if there are two consecutive cert change happening very quickly? Then we might use two different SSLContext builder to initialize the pool since when the second `reload` calls `connpool.clear`, the first call to `getChannel` might still not start to initialize the pool.

the first thread will fail while the connection user uses it, and then a retry is expected.

File: src/main/java/org/tikv/common/util/ChannelFactory.java [hunk 2]
```diff
@@ -215,63 +216,69 @@ public ChannelFactory(
...
+
+    if (sslContextBuilder == null) {
+      return builder.usePlaintext().build();
+    } else {
+      SslContext sslContext;
+      try {
+        sslContext = sslContextBuilder.build();
+      } catch (SSLException e) {
+        logger.error("create ssl context failed!", e);
+        return null;
```
Comment (zhangyangyu) [inline src/main/java/org/tikv/common/util/ChannelFactory.java:251]: `return null` or `raise exception`? What should the user expect and how they could restore?

File: src/main/java/org/tikv/common/util/ChannelFactory.java [hunk 3]
```diff
@@ -215,63 +216,69 @@ public ChannelFactory(
...
-      logger.info("invalidate connection pool");
+  @VisibleForTesting
+  public synchronized ManagedChannel reload(String address, HostMapping mapping) {
+    assert certContext != null;
+    // TODO: use WatchService to detect file change.
+    if (certContext.isModified()) {
+      logger.info("certificate file changed, reloading");
+      sslContextBuilder.set(certContext.createSslContextBuilder());
       connPool.clear();
+      return connPool.computeIfAbsent(
```
Comment (xuanyu66) [inline src/main/java/org/tikv/common/util/ChannelFactory.java:265]: It's more reasonable to make the method `reload` void, there is already logic in getChannel() that creates a channel. It can make code more readable

Comment (zhangyangyu) [inline src/main/java/org/tikv/common/util/ChannelFactory.java:265]: Maybe we could add a comment here explaining why we double the creation logic in case anyone in future think it's redundant and delete it :-(

File: src/main/java/org/tikv/common/util/ChannelFactory.java [hunk 4]
```diff
@@ -215,63 +216,69 @@ public ChannelFactory(
...
+      return builder.sslContext(sslContext).build();
     }
-    return false;
   }
 
-  public ManagedChannel getChannel(String addressStr, HostMapping hostMapping) {
-    if (reloadSslContext()) {
-      logger.info("invalidate connection pool");
+  @VisibleForTesting
+  public synchronized ManagedChannel reload(String address, HostMapping mapping) {
```
Comment (xuanyu66) [inline src/main/java/org/tikv/common/util/ChannelFactory.java:258]: I am worried about the performance of getChannel(). Since renewing cert is a very low frequent operation, it's a big cost to sync and invoke a disk IO every time

Comment (xuanyu66) [reply src/main/java/org/tikv/common/util/ChannelFactory.java:258]: And from my point of view, client-java needs to have a high throughput when working as a cache client.
It's a situation quite like service discovery in RPC client, in which we wouldn't refresh every time getChannel

Comment (iosmanthus) [reply src/main/java/org/tikv/common/util/ChannelFactory.java:258]: > 

There is an optimization to avoid sync disk IO, using a `WatchService` to notify the `ChannelFactory` if the cert is changed. A TODO  is added.

File: src/main/java/org/tikv/common/util/ChannelFactory.java (hunk 3 above)
Comment (iosmanthus) [reply src/main/java/org/tikv/common/util/ChannelFactory.java:265]: Done.

File: src/main/java/org/tikv/common/util/ChannelFactory.java (hunk 2 above)
Comment (iosmanthus) [reply src/main/java/org/tikv/common/util/ChannelFactory.java:251]: change to `raise exception`.

File: src/main/java/org/tikv/common/util/ChannelFactory.java (hunk 4 above)
Comment (xuanyu66) [reply src/main/java/org/tikv/common/util/ChannelFactory.java:258]: Would you enhance it recently?

File: src/main/java/org/tikv/common/util/ChannelFactory.java [hunk 5]
```diff
@@ -26,80 +26,160 @@
...
-        logger.info("reload ssl context");
-        return createSslContextBuilder();
+    private void watchLoop() {
+      try {
+        WatchService watchService = FileSystems.getDefault().newWatchService();
+        Path p = Paths.get(path);
+        p.register(watchService, StandardWatchEventKinds.ENTRY_MODIFY);
+
+        WatchKey key;
+        while ((key = watchService.take()) != null) {
```
Comment (xuanyu66) [inline src/main/java/org/tikv/common/util/ChannelFactory.java:101]: Under which condition would equal null?

File: src/main/java/org/tikv/common/util/ChannelFactory.java [hunk 6]
```diff
@@ -26,80 +26,160 @@
...
+          boolean changed = false;
+          OUTER:
+          for (WatchEvent<?> event : key.pollEvents()) {
+            for (String target : targets) {
+              logger.info("detected file change: {}", event.context());
+              if (event.context().toString().equals(target)) {
+                changed = true;
+                break OUTER;
```
Comment (xuanyu66) [inline src/main/java/org/tikv/common/util/ChannelFactory.java:109]: Why break here?

File: src/main/java/org/tikv/common/util/ChannelFactory.java [hunk 7]
```diff
@@ -26,80 +26,160 @@
...
+  private int connRecycleTime;
   private final int maxFrameSize;
   private final int keepaliveTime;
   private final int keepaliveTimeout;
   private final int idleTimeout;
-  private final ConcurrentHashMap<String, ManagedChannel> connPool = new ConcurrentHashMap<>();
   private final CertContext certContext;
+
+  @VisibleForTesting
+  public final ConcurrentHashMap<Pair<SslContextBuilder, String>, ManagedChannel> connPool =
```
Comment (xuanyu66) [inline src/main/java/org/tikv/common/util/ChannelFactory.java:70]: The key of Map doesn't implement hashCode() and equals(). Will it bring some potential bugs?

**Review by xuanyu66 — CHANGES_REQUESTED** [review]

**Comment by xuanyu66** [comment]
@shiyuhang0 PTAL

File: src/main/java/org/tikv/common/util/ChannelFactory.java (hunk 6 above)
Comment (iosmanthus) [reply src/main/java/org/tikv/common/util/ChannelFactory.java:109]: If all the certs in the base path change in one shot, multiple events will be triggered. If we consume all of these events one by one, multiple reload will be triggered. This `break` controls a list of events that will trigger only once reload.

File: src/main/java/org/tikv/common/util/ChannelFactory.java (hunk 5 above)
Comment (iosmanthus) [reply src/main/java/org/tikv/common/util/ChannelFactory.java:101]: https://docs.oracle.com/javase/7/docs/api/java/nio/file/WatchService.html#take() should always return notnull seem this null check is redundant.

File: src/main/java/org/tikv/common/util/ChannelFactory.java (hunk 7 above)
Comment (iosmanthus) [reply src/main/java/org/tikv/common/util/ChannelFactory.java:70]: I will wrap SslContextBuilder into a type with epoch.

**Comment by iosmanthus** [comment]
@xuanyu66 PTAL

**Comment by xuanyu66** [comment]
@iosmanthus Plz check the failed CI tests

File: src/main/java/org/tikv/common/util/ChannelFactory.java [hunk 8]
```diff
@@ -26,80 +26,198 @@
...
+      try {
+        WatchService watchService = FileSystems.getDefault().newWatchService();
+        Path p = Paths.get(path);
+        p.register(watchService, StandardWatchEventKinds.ENTRY_MODIFY);
+
+        while (true) {
+          WatchKey key = watchService.take();
+          boolean changed = false;
+          OUTER:
+          for (WatchEvent<?> event : key.pollEvents()) {
```
Comment (xuanyu66) [inline src/main/java/org/tikv/common/util/ChannelFactory.java:138]: key.pollEvents() is non-blocking, which maybe waste CPU resource

File: src/main/java/org/tikv/common/util/ChannelFactory.java [hunk 9]
```diff
@@ -212,72 +319,122 @@ public ChannelFactory(
...
   }
 
-  public ManagedChannel getChannel(String addressStr, HostMapping hostMapping) {
-    if (reloadSslContext()) {
-      logger.info("invalidate connection pool");
-      connPool.clear();
+  private void cleanExpireConn(Collection<ManagedChannel> pending) {
+    for (ManagedChannel channel : pending) {
+      logger.info("cleaning expire channels");
+      channel.shutdownNow();
```
Comment (xuanyu66) [inline src/main/java/org/tikv/common/util/ChannelFactory.java:368]: Why use shutdownNow()? Maybe some channel is being used right now

File: src/main/java/org/tikv/common/util/ChannelFactory.java (hunk 8 above)
Comment (iosmanthus) [reply src/main/java/org/tikv/common/util/ChannelFactory.java:138]: this method will not keep running, once the events were taken out of the queue, this block will exist and wait at `watchService.take()`

File: src/main/java/org/tikv/common/util/ChannelFactory.java (hunk 9 above)
Comment (iosmanthus) [reply src/main/java/org/tikv/common/util/ChannelFactory.java:368]: If the channel is used right now, no matter calling shutdown or `shutdownNow`, the user of the channel will receive an exception, a retry is expected.

**Comment by iosmanthus** [comment]
> @iosmanthus Plz check the failed CI tests

Fixed, it's broken by the wrong initial state of `ChannelFactory`.

File: src/main/java/org/tikv/common/util/ChannelFactory.java [hunk 10]
```diff
@@ -26,80 +26,198 @@
...
+    }
 
-    public SslContextBuilder reload() {
-      if (isModified()) {
-        logger.info("reload ssl context");
-        return createSslContextBuilder();
+    public boolean isModified() throws Exception {
+      boolean modified = !notify.isEmpty();
+      if (modified) {
+        notify.take();
```
Comment (zhangyangyu) [inline src/main/java/org/tikv/common/util/ChannelFactory.java:173]: Maybe better to use `clear`? If there are multiple `true`s in it, no need to trigger reload multiple times.

File: src/main/java/org/tikv/common/util/ChannelFactory.java [hunk 11]
```diff
@@ -212,72 +319,122 @@ public ChannelFactory(
...
+      sslContextBuilder.set(new Epoch<>(certContext.createSslContextBuilder(), epoch++));
+
+      Collection<ManagedChannel> pending = new HashSet<>();
+      for (Map.Entry<Pair<Epoch<SslContextBuilder>, String>, ManagedChannel> pair :
+          connPool.entrySet()) {
+        Epoch<SslContextBuilder> b = pair.getKey().getLeft();
+        if (b != sslContextBuilder.get()) {
+          pending.add(pair.getValue());
+          connPool.remove(pair.getKey());
+          connPool.computeIfAbsent(
```
Comment (zhangyangyu) [inline src/main/java/org/tikv/common/util/ChannelFactory.java:393]: I don't get why we need to `computeIfAbsent` twice in reload.

**Comment by zhangyangyu** [comment]
Given the complexity of current implementation, how do you folks think of using the simplest way to achieve it? A polling thread polls at fixed interval, like [org.apache.hadoop.security.ssl. ReloadingX509TrustManager](https://github.com/apache/hadoop/blob/d4fd675a95c16f6ecd8d8514cc3c0bef34bc9eff/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/ReloadingX509TrustManager.java). Make it optional let users open it and set interval. >_<!

**Comment by iosmanthus** [comment]
> Given the complexity of current implementation and IMHO it's hard to reason about/understand/maintain(hard to make concurrency programming right), also break change the TLS configurations and `ChannelFactory` API :(, how do you folks think of using the simplest way to achieve it? A polling thread polls at fixed interval, like [org.apache.hadoop.security.ssl.ReloadingX509TrustManager](https://github.com/apache/hadoop/blob/d4fd675a95c16f6ecd8d8514cc3c0bef34bc9eff/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/security/ssl/ReloadingX509TrustManager.java). Make it optional, let users open it and set interval. >_<!

All the complexity come from the conn pool, even with a simple poll loop to refresh SSL context.

File: src/main/java/org/tikv/common/util/ChannelFactory.java (hunk 9 above)
Comment (xuanyu66) [reply src/main/java/org/tikv/common/util/ChannelFactory.java:368]: got it

File: src/main/java/org/tikv/common/util/ChannelFactory.java (hunk 8 above)
Comment (xuanyu66) [reply src/main/java/org/tikv/common/util/ChannelFactory.java:138]: Got it

**Review by xuanyu66 — DISMISSED** [review]

**Comment by iosmanthus** [comment]
@zhangyangyu PTAL

File: src/main/java/org/tikv/common/util/ChannelFactory.java [hunk 12]
```diff
@@ -188,22 +199,39 @@ public ChannelFactory(
...
         new OpenSslContext(trustCertCollectionFilePath, keyCertChainFilePath, keyFilePath);
+
+    File trustCert = new File(trustCertCollectionFilePath);
+    File keyCert = new File(keyCertChainFilePath);
+    File key = new File(keyFilePath);
+
+    if (certReloadInterval > 0) {
+      onCertChange();
+      this.certWatcher =
+          new CertWatcher(1, ImmutableList.of(trustCert, keyCert, key), this::onCertChange);
```
Comment (shiyuhang0) [inline src/main/java/org/tikv/common/util/ChannelFactory.java:222]: why we set interval as 1 in openssl

File: src/main/java/org/tikv/common/util/ChannelFactory.java [hunk 13]
```diff
@@ -188,22 +199,39 @@ public ChannelFactory(
...
+      this.certWatcher = null;
+    }
   }
 
   public ChannelFactory(
       int maxFrameSize,
       int keepaliveTime,
       int keepaliveTimeout,
       int idleTimeout,
+      long connRecycleTime,
```
Comment (shiyuhang0) [inline src/main/java/org/tikv/common/util/ChannelFactory.java:233]: I don't understand why a connRecycleTime delay is needed when recycling connections. Can you explain this configuration

File: src/main/java/org/tikv/common/util/ChannelFactory.java [hunk 14]
```diff
@@ -40,66 +47,93 @@
...
-    public SslContextBuilder reload() {
-      if (isModified()) {
-        logger.info("reload ssl context");
-        return createSslContextBuilder();
+    private boolean needReload() {
+      boolean needReload = false;
+      // Check all the modification of the `targets`.
+      // If one of them changed, means to need reload.
+      for (int i = 0; i < targets.size(); i++) {
+        long lastModified = targets.get(i).lastModified();
```
Comment (zhangyangyu) [inline src/main/java/org/tikv/common/util/ChannelFactory.java:101]: `lastModified` might raise error due to permission. Maybe we need to catch the whole `needReload` body to give a meaningful error log?

File: src/main/java/org/tikv/common/util/ChannelFactory.java [hunk 15]
```diff
@@ -320,8 +239,46 @@ public ChannelFactory(
...
+  }
+
+  private void onCertChange() {
+    try {
+      SslContextBuilder newBuilder = certContext.createSslContextBuilder();
+      lock.writeLock().lock();
+      sslContextBuilder.set(newBuilder);
+
+      List<ManagedChannel> pending = new ArrayList<>(connPool.values());
+      recycler.schedule(() -> cleanExpireConn(pending), connRecycleTime, TimeUnit.SECONDS);
```
Comment (xuanyu66) [inline src/main/java/org/tikv/common/util/ChannelFactory.java]: Since recycler is single-thread and prev task is still running even if cleaning was done.
So the interval of the current task is n*connRecycleTime(n is the number of tasks in the recycler).
https://blog.csdn.net/weixin_38106322/article/details/104494106

File: src/main/java/org/tikv/common/util/ChannelFactory.java (hunk 12 above)
Comment (iosmanthus) [reply src/main/java/org/tikv/common/util/ChannelFactory.java:222]: It's a miss typing, change to `certReloadInterval`.

File: src/main/java/org/tikv/common/util/ChannelFactory.java (hunk 13 above)
Comment (iosmanthus) [reply src/main/java/org/tikv/common/util/ChannelFactory.java:233]: Comments will be added, and the old channel will work for a while even if the certificate is reloaded but it should not be used forever, this recycle time is about to force those expired channels to close and use the latest context after a specific waiting duration.

Comment (shiyuhang0) [reply src/main/java/org/tikv/common/util/ChannelFactory.java:233]: get

File: src/main/java/org/tikv/common/util/ChannelFactory.java [hunk 16]
```diff
@@ -212,72 +240,110 @@ public ChannelFactory(
...
+
+  private void cleanExpiredConn(List<ManagedChannel> pending) {
+    for (ManagedChannel channel : pending) {
+      logger.info("cleaning expire channels");
+      channel.shutdownNow();
+      while (!channel.isShutdown()) {
+        try {
+          channel.awaitTermination(5, TimeUnit.SECONDS);
+        } catch (Exception e) {
+          logger.info("recycle channels timeout:", e);
```
[the remark this answers is not in the document]
Comment (iosmanthus) [reply src/main/java/org/tikv/common/util/ChannelFactory.java:332]: Changed to `warn`.

File: src/main/java/org/tikv/common/region/StoreHealthyChecker.java [hunk 17]
```diff
@@ -96,6 +96,7 @@ private boolean checkStoreTombstone(TiStore store) {
         return true;
       }
     } catch (Exception e) {
+      logger.info("fail to check tombstone stores {}", e.toString());
```
[the remark this answers is not in the document]
Comment (iosmanthus) [reply src/main/java/org/tikv/common/region/StoreHealthyChecker.java:99]: Done.

File: src/main/java/org/tikv/common/util/ChannelFactory.java (hunk 14 above)
Comment (iosmanthus) [reply src/main/java/org/tikv/common/util/ChannelFactory.java:101]: Done.

**Comment by iosmanthus** [comment]
@zhangyangyu @xuanyu66 @sunxiaoguang @shiyuhang0 PTAL

**Review by xuanyu66 — APPROVED** [review]

**Review by shiyuhang0 — APPROVED** [review]

File: src/main/java/org/tikv/common/util/ChannelFactory.java [hunk 18]
```diff
@@ -26,80 +26,198 @@
...
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
 import org.tikv.common.HostMapping;
 import org.tikv.common.pd.PDUtils;
 
 public class ChannelFactory implements AutoCloseable {
   private static final Logger logger = LoggerFactory.getLogger(ChannelFactory.class);
+  private static final String PUB_KEY_INFRA = "PKIX";
 
+  private int connRecycleTime;
```
[the remark this answers is not in the document]
Comment (iosmanthus) [reply src/main/java/org/tikv/common/util/ChannelFactory.java]: Done.

**Review by sunxiaoguang — DISMISSED** [review]

**Review by sunxiaoguang — APPROVED** [review]
