### PR TITLE
All keepTiKVToImportMode after stopped

### LINKED ISSUE #282: keepTiKVToImportMode cannot be called after stopKeepTiKVToImportMode
**What did you do**
```java
        TiConfiguration tiConf = TiConfiguration.createDefault("127.0.0.1:2379");
        TiSession tiSession = TiSession.create(tiConf);
        for (int i = 0; i < 2; i++) {
            SwitchTiKVModeClient switchTiKVModeClient = tiSession.getSwitchTiKVModeClient();
            switchTiKVModeClient.keepTiKVToImportMode();
            Thread.sleep(6000);
            switchTiKVModeClient.stopKeepTiKVToImportMode();
            switchTiKVModeClient.switchTiKVToNormalMode();
        }
```

**What happens**
```
Exception in thread "main" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@37afeb11 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@515aebb0[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:573)
	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.scheduleAtFixedRate(Executors.java:735)
	at org.tikv.common.importer.SwitchTiKVModeClient.keepTiKVToImportMode(SwitchTiKVModeClient.java:59)
```

**Java Client and TiDB/TiKV version info**

3.2.0-SNAPSHOT (37506fe)

### PR DESCRIPTION
**Pull request by peng1999**
Signed-off-by: Peng Guanwen <pg999w@outlook.com>

### What problem does this PR solve? 

Fixes #282

### What is changed and how it works?

The scheduler got removed after stopping.

### Check List 

Tests 

 - Integration test

### CODE REVIEW

File: src/main/java/org/tikv/common/importer/SwitchTiKVModeClient.java [hunk 1]
```diff
@@ -36,32 +36,34 @@
...
   }
 
   public void switchTiKVToNormalMode() {
     doSwitchTiKVMode(ImportSstpb.SwitchMode.Normal);
   }
 
   public void keepTiKVToImportMode() {
-    ingestScheduledExecutorService.scheduleAtFixedRate(
-        this::switchTiKVToImportMode, 0, KEEP_TIKV_TO_IMPORT_MODE_PERIOD, TimeUnit.SECONDS);
+    if (ingestScheduledExecutorService == null) {
```
Comment (marsishandsome) [inline src/main/java/org/tikv/common/importer/SwitchTiKVModeClient.java:52]: add `synchronized` here to support Thread-safe ?

File: src/main/java/org/tikv/common/importer/SwitchTiKVModeClient.java [hunk 2]
```diff
@@ -36,32 +36,34 @@
...
+                  .setDaemon(true)
+                  .build());
+      ingestScheduledExecutorService.scheduleAtFixedRate(
+          this::switchTiKVToImportMode, 0, KEEP_TIKV_TO_IMPORT_MODE_PERIOD, TimeUnit.SECONDS);
+    }
   }
 
   public void stopKeepTiKVToImportMode() {
     ingestScheduledExecutorService.shutdown();
+    ingestScheduledExecutorService = null;
```
Comment (marsishandsome) [inline src/main/java/org/tikv/common/importer/SwitchTiKVModeClient.java:66]: add `synchronized` here to support Thread-safe ?

**Review by marsishandsome — APPROVED** [review]
LGTM
