### PR TITLE
[close #749] Fix health checking issue

### LINKED ISSUE #749: CheckStoreHealth does not work wtih TiFlash
### 1. Describe the bug

The checkStoreHealth method in StoreHealthyChecker will check the status of the store periodically.

However, the check for TiFlash always fails and returns false because TiFlash does not provide the grpc health checking service. See here for more details about [GRPC Health Checking Protocol](https://grpc.github.io/grpc/core/md_doc_health-checking.html)

Thus, the status of TiFlash will always be unreachable.

### 5. What are your Java Client and TiKV versions? (Required)

- Client Java: <= 3..3.4
- TiKV: any version

### PR DESCRIPTION
**Pull request by shiyuhang0**
### What problem does this PR solve?

Issue Number: close #749

https://github.com/pingcap/tispark/issues/2707

Problem Description: StoreHealthyChecker fails to check the status of TiFlash

### What is changed and how does it work?

Use isMppalive RPC to probe the status of TiFlash.

### Check List for Tests

Manual test：

I have tested this locally with TiSpark. TiSpark will request TiFlash using client-java

1. TiSpark will with the client-java before  this PR will throw errors even if TiFlash is alive

```
23/05/20 15:31:12 WARN StoreHealthyChecker: fail to check TiFlash health, regrade as unhealthy
org.tikv.shade.io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 1.999882667s. [closed=[], open=[[buffered_nanos=2005712916, waiting_for_connection]]]
	at org.tikv.shade.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:287)
	at org.tikv.shade.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:268)
	at org.tikv.shade.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:175)
	at org.tikv.common.region.StoreHealthyChecker.checkTiFlashHealth(StoreHealthyChecker.java:99)
	at org.tikv.common.region.StoreHealthyChecker.checkStoreHealth(StoreHealthyChecker.java:86)
	at org.tikv.common.region.StoreHealthyChecker.run(StoreHealthyChecker.java:154)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
23/05/20 15:31:13 WARN RangeSplitter: Cannot find valid store on TiFlash(engine=tiflash)
```

2. TiSpark success with the client-java build by this pr

### Side effects

- Possible performance regression, WHY: **TBD**
- Increased code complexity, WHY: **TBD**
- Breaking backward compatibility, WHY: **TBD**
- NO side effects

### Related changes

- Need to cherry-pick to the release branch
- Need to update the documentation
- Need to be included in the release note
- NO related changes

### CODE REVIEW

**Review by xuanyu66 — DISMISSED** [review]

File: src/main/java/org/tikv/common/region/RegionManager.java [hunk 1]
```diff
@@ -235,10 +235,12 @@ public Pair<TiRegion, TiStore> getRegionStorePairByKey(
         store = getStoreById(peer.getStoreId(), backOffer);
         if (store.isReachable()) {
           // update replica's index
+          logger.info("Store {} is reachable, use it as store", peer.getStoreId());
```
Comment (iosmanthus) [inline src/main/java/org/tikv/common/region/RegionManager.java:238]:
```suggestion
          logger.info("Store {} is reachable, select it", peer.getStoreId());
```

**Review by iosmanthus — DISMISSED** [review]

File: src/main/java/org/tikv/common/region/StoreHealthyChecker.java [hunk 2]
```diff
@@ -75,6 +80,33 @@ private List<TiStore> getValidStores() {
 
   private boolean checkStoreHealth(TiStore store) {
     String addressStr = store.getStore().getAddress();
+    for (Metapb.StoreLabel label : store.getStore().getLabelsList()) {
```
Comment (pingyu) [inline src/main/java/org/tikv/common/region/StoreHealthyChecker.java:83]: Suggest to wrap as a new method (e.g. `isTiFLash`) of `TiStore`.

File: src/main/java/org/tikv/common/region/StoreHealthyChecker.java [hunk 3]
```diff
@@ -75,6 +80,33 @@ private List<TiStore> getValidStores() {
...
+      TikvGrpc.TikvBlockingStub stub =
+          TikvGrpc.newBlockingStub(channel).withDeadlineAfter(timeout, TimeUnit.MILLISECONDS);
+      Supplier<IsAliveRequest> factory = () -> Mpp.IsAliveRequest.newBuilder().build();
+      Mpp.IsAliveResponse resp =
+          ClientCalls.blockingUnaryCall(
+              stub.getChannel(), TikvGrpc.getIsAliveMethod(), stub.getCallOptions(), factory.get());
+      return resp != null && resp.getAvailable();
+    } catch (Exception e) {
+      logger.warn(
+          "fail to check TiFlash health, regrade as unhealthy. TiFlash address: " + addressStr, e);
```
Comment (pingyu) [inline src/main/java/org/tikv/common/region/StoreHealthyChecker.java:104]: "regrade" -> "regard" ?

File: src/main/java/org/tikv/common/region/StoreHealthyChecker.java [hunk 4]
```diff
@@ -83,6 +115,8 @@ private boolean checkStoreHealth(TiStore store) {
       HealthCheckResponse resp = stub.check(req);
       return resp.getStatus() == HealthCheckResponse.ServingStatus.SERVING;
     } catch (Exception e) {
+      logger.warn(
+          "fail to check TiKV health, regrade as unhealthy. TiKV address: " + addressStr, e);
```
Comment (pingyu) [inline src/main/java/org/tikv/common/region/StoreHealthyChecker.java:119]: Ditto.

File: src/main/java/org/tikv/common/region/RegionManager.java (hunk 1 above)
Comment (shiyuhang0) [reply src/main/java/org/tikv/common/region/RegionManager.java]: this log is moved to another pr now. because it is not a part of health check

**Review by pingyu — APPROVED** [review]
LGTM~
