### PR TITLE
[close #446] Fix Optional fields type

### LINKED ISSUE #446: TiConfiguration can not be serialize
### 1. Describe the bug

When I use the client in Flink , I get an error with TiConfiguration 

### 2. Minimal reproduce step (Required)

serialize TiConfiguration

### 3. What did you see instead (Required)

```
Caused by: java.io.NotSerializableException: java.util.Optional
  at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)
  at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
  at org.apache.flink.util.InstantiationUtil.serializeObject(InstantiationUtil.java:624)
  at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:143)
  ... 48 more
```

### 4. What did you expect to see? (Required)

TiConfiguration is serialized normally

### 5. What is your Java Client and TiKV version? (Required)

- Client Java: master
- TiKV: v5.x

### PR DESCRIPTION
**Pull request by zhongqishang**
Signed-off-by: Qishang Zhong <zhongqishang@gmail.com>

### What problem does this PR solve?

When I use the client in Flink , I get an error

```
Caused by: java.io.NotSerializableException: java.util.Optional
  at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)
  at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
  at org.apache.flink.util.InstantiationUtil.serializeObject(InstantiationUtil.java:624)
  at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:143)
  ... 48 more
```

### What is changed and how it works?

Optional in the getter method

### Check List for Tests

This PR has been tested by the at least one of the following methods:
- Unit test

### Side effects

- NO side effects

### Related changes

- NO related changes

https://stackoverflow.com/questions/24547673/why-java-util-optional-is-not-serializable-how-to-serialize-the-object-with-suc

### CODE REVIEW

**Review by marsishandsome — APPROVED** [review]
LGTM

**Comment by zz-jason** [comment]
@zhongqishang thanks for your contribution, please create an issue that you wish to fix and follow the PR title format

**Comment by zz-jason** [comment]
could you also add some tests?

**Comment by zhongqishang** [comment]
@zz-jason I have created an issue and added the tests.

File: src/main/java/org/tikv/common/TiConfiguration.java [hunk 1]
```diff
@@ -360,12 +360,12 @@ private static ReplicaRead getReplicaRead(String key) {
   private int rawKVBatchWriteTimeoutInMS = getInt(TIKV_RAWKV_BATCH_WRITE_TIMEOUT_IN_MS);
   private int rawKVScanTimeoutInMS = getInt(TIKV_RAWKV_SCAN_TIMEOUT_IN_MS);
   private int rawKVCleanTimeoutInMS = getInt(TIKV_RAWKV_CLEAN_TIMEOUT_IN_MS);
-  private Optional<Integer> rawKVReadSlowLogInMS = getIntOption(TIKV_RAWKV_READ_SLOWLOG_IN_MS);
-  private Optional<Integer> rawKVWriteSlowLogInMS = getIntOption(TIKV_RAWKV_WRITE_SLOWLOG_IN_MS);
-  private Optional<Integer> rawKVBatchReadSlowLogInMS =
-      getIntOption(TIKV_RAWKV_BATCH_READ_SLOWLOG_IN_MS);
-  private Optional<Integer> rawKVBatchWriteSlowLogInMS =
-      getIntOption(TIKV_RAWKV_BATCH_WRITE_SLOWLOG_IN_MS);
+  private Integer rawKVReadSlowLogInMS = getIntOption(TIKV_RAWKV_READ_SLOWLOG_IN_MS).orElse(null);
```
Comment (zz-jason) [inline src/main/java/org/tikv/common/TiConfiguration.java:363]: I'm a little confused. why not set the type to `int` and get the value via `getInt()` just like what we did for `rawKVCleanTimeoutInMS`?

@marsishandsome do you have any idea?

Comment (zhongqishang) [reply src/main/java/org/tikv/common/TiConfiguration.java:363]: I think `rawKVReadSlowLogInMS` not set default value in `org.tikv.common.TiConfiguration#loadFromDefaultProperties`, and rawKVReadSlowLogInMS must be have a default value due to `org.tikv.common.log.SlowLogImpl#log`.

Comment (marsishandsome) [reply src/main/java/org/tikv/common/TiConfiguration.java:363]: `rawKVReadSlowLogInMS` is calculated as follows:
1.  if `TIKV_RAWKV_READ_SLOWLOG_IN_MS` is set, then use it, in such case `rawKVReadSlowLogInMS` != null
2. else use `getTimeout() * 2`, in such case `rawKVReadSlowLogInMS` == null

Comment (zz-jason) [reply src/main/java/org/tikv/common/TiConfiguration.java:363]: OK.

**Review by zz-jason — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
