### PR TITLE
[close #489 ] fix backoffer data race

### LINKED ISSUE #489: HashMap throw a ConcurrentModificationException
### 1. Describe the bug
When use rawkv-migration-tool to import data for TiKV, it threw ConcurrentModificationException 
image

HashMap throws ConcurrentModificationException in certain scene, such as [this](https://stackoverflow.com/questions/54824656/since-java-9-hashmap-computeifabsent-throws-concurrentmodificationexception-on)

### 5. What is your Java Client and TiKV version? (Required)
3.1.11
- Client Java:
- TiKV:

### PR DESCRIPTION
**Pull request by iosmanthus**
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>

### What problem does this PR solve?

Issue Number: close #489

`ConcreteBackOffer` may trigger by multiple threads but the `backOffFunctionMap` is `HashMap` which is not thread-safe. This might trigger a race exception while this backoffer is shared between threads.

### CODE REVIEW

**Review by marsishandsome — APPROVED** [review]
LGTM

File: src/main/java/org/tikv/common/util/ConcreteBackOffer.java [hunk 1]
```diff
@@ -37,8 +39,11 @@
 public class ConcreteBackOffer implements BackOffer {
   private static final Logger logger = LoggerFactory.getLogger(ConcreteBackOffer.class);
   private final int maxSleep;
-  private final Map<BackOffFunction.BackOffFuncType, BackOffFunction> backOffFunctionMap;
-  private final List<Exception> errors;
+
+  @VisibleForTesting
+  public final Map<BackOffFunction.BackOffFuncType, BackOffFunction> backOffFunctionMap;
+
+  @VisibleForTesting public final List<Exception> errors;
```
Comment (zz-jason) [inline src/main/java/org/tikv/common/util/ConcreteBackOffer.java:46]:
```suggestion
  @VisibleForTesting
  public final List<Exception> errors;
```

Comment (iosmanthus) [reply src/main/java/org/tikv/common/util/ConcreteBackOffer.java:46]: It is `./dev/javafmt` format the code this way.

**Review by zz-jason — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
