### PR TITLE
[close #736] Select reachable store

### LINKED ISSUE #736: Missing fallback mechanism for replica selection
### 1. Describe the bug

When there are multiple replica candidates, and the first one has already failed to respond, the caller does not try the next one on the list.

### 2. Minimal reproduce step (Required)

1. Use leader and follower replica selector
2. Use follower read
3. Kill the store that hosts the target follower before sending the request

### 3. What did you see instead (Required)

As stated in the bug description.

### 4. What did you expect to see? (Required)

Try the next replica candidate

### 5. What are your Java Client and TiKV versions? (Required)

- Client Java: 6.5
- TiKV: 6.5

Ideally, it is expected to see that a request trys to connect to the first replica candidate on the list, retry for several times or a certain period of time on the same target when it is unavailable (considering transient error and rate limiting are quite normal on the TiKV side), then fallback to the next one on the list if the first candidate is still unavailable.

### PR DESCRIPTION
**Pull request by shiyuhang0**
### What problem does this PR solve?

Issue Number: close #736

### What is changed and how does it work?

Judge store status before use. Use the next replica when the current replica is unreachable.

### Test

I have tested in TiSpark follower read with the first store killed, its success to request the next store.

### CODE REVIEW

**Review by zhangyangyu — APPROVED** [review]

File: src/main/java/org/tikv/common/region/RegionManager.java [hunk 1]
```diff
@@ -228,12 +228,25 @@ public Pair<TiRegion, TiStore> getRegionStorePairByKey(
 
     TiStore store = null;
     if (storeType == TiStoreType.TiKV) {
-      Peer peer = region.getCurrentReplica();
-      store = getStoreById(peer.getStoreId(), backOffer);
+      // check from the first replica in case it recovers
+      List<Peer> replicaList = region.getReplicaList();
+      for (int i = 0; i < replicaList.size(); i++) {
+        Peer peer = replicaList.get(i);
+        store = getStoreById(peer.getStoreId(), backOffer);
```
Comment (pingyu) [inline src/main/java/org/tikv/common/region/RegionManager.java:235]: Is it possible to make replicas not balance ? As we always try the replica 0 at first.

How about start from `getCurrentReplica()`, then if the current replica is not available, get next one by `getNextReplica` and retry.

Comment (shiyuhang0) [reply src/main/java/org/tikv/common/region/RegionManager.java:235]: There are two problems if we getNextReplica.
1. code will trap into endless loop when there is no available store.
2. assume we set `follower,leader`, the replica list will begin with the followers then the leaders.  If we getNextReplica, we may miss the recover follower and request the leader

Comment (pingyu) [reply src/main/java/org/tikv/common/region/RegionManager.java:235]: > 1. code will trap into endless loop when there is no available store.

It is not difficult to be solved by loop no more than `replicaList.size()` times.

> 2. assume we set `follower,leader`, the replica list will begin with the followers then the leaders.  If we getNextReplica, we may miss the recover follower and request the leader

Why we should not "miss the recover follower and request the leader" ? If we don't want to read on leader, we can set the replica selector as "followers only". Otherwise, if "leader and follower" is used, it should be OK to read on leader.

> Besides, the original code always select the first one. also has the issue of balance

I also feel strange that why `getNextReplica` is unused, and except which `replicaIdx` is changed nowhere. Any idea @iosmanthus ?

Comment (zhangyangyu) [reply src/main/java/org/tikv/common/region/RegionManager.java:235]: The customer wants a "fallback" strategy. They want to read followers first to isolate dump traffic. But if all the followers are down, fallback to leaders as a cover.

So if "follower and leader" is specified, it means use followers first, and then leaders. The order matters.

Comment (pingyu) [reply src/main/java/org/tikv/common/region/RegionManager.java:235]: Is stale read enabled ? If not, when all followers are down, the leader is also unavailable (neither readable nor writable as well, see https://www.pingcap.com/blog/lease-read/)

Comment (zhangyangyu) [reply src/main/java/org/tikv/common/region/RegionManager.java:235]: Ahh, I think we take some terms wrong, it's not follower, it's learner, who will not attend voting. And yes, this is for stale read. The normal TiKV nodes will still take leader and follower and handle online traffic. And there will be extra learner nodes dedicated for offline traffic. When learners are down, goes for the normal nodes.
