### PR TITLE
[close #663] Select TiFlash Stores Round-Robin

### LINKED ISSUE #663: Always select the first TiFlash store.
### 1. Describe the bug

when there are more than one TiFlash replicas, client-java always chooses the first TiFlash store

### 5. What are your Java Client and TiKV versions? (Required)

- Client Java: master
- TiKV: master

### PR DESCRIPTION
**Pull request by shiyuhang0**
### What problem does this PR solve?

Problem Description: **client-java always selects the first TiFlash store which may cause read hotspot.**

### What is changed and how does it work?

Choose the TiFlash stores Round-Robin

### Code changes

- Has exported function/method change
- Has exported variable/fields change
- Has methods of interface change
- Has persistent data change
- No code

### Check List for Tests

This PR has been tested by at least one of the following methods:
- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Side effects

- Possible performance regression, WHY: **TBD**
- Increased code complexity, WHY: **TBD**
- Breaking backward compatibility, WHY: **TBD**
- NO side effects

### Related changes

- Need to cherry-pick to the release branch
- Need to update the documentation
- Need to be included in the release note
- NO related changes

### CODE REVIEW

File: src/main/java/org/tikv/common/region/RegionManager.java [hunk 1]
```diff
@@ -68,6 +68,7 @@ public class RegionManager {
   private final TiConfiguration conf;
   private final ScheduledExecutorService executor;
   private final StoreHealthyChecker storeChecker;
+  private int TiFlashStoreIndex = 0;
```
Comment (iosmanthus) [inline src/main/java/org/tikv/common/region/RegionManager.java:71]:
```suggestion
  private int tiflashStoreIdx = 0;
```

File: src/main/java/org/tikv/common/region/RegionManager.java [hunk 2]
```diff
@@ -191,17 +192,23 @@ public Pair<TiRegion, TiStore> getRegionStorePairByKey(
...
-            break outerLoop;
+            tiflashStores.add(s);
           }
         }
       }
+      // select a tiflash with RR strategy
+      if (tiflashStores.size() > 0) {
+        store =
+            tiflashStores.get(TiFlashStoreIndex > tiflashStores.size() - 1 ? 0 : TiFlashStoreIndex);
+        TiFlashStoreIndex++;
```
Comment (iosmanthus) [inline src/main/java/org/tikv/common/region/RegionManager.java:209]: Considering the method `getRegionStorePairByKey` might call by multiple threads, we might change the idx member to be atomic.

**Review by zhangyangyu — DISMISSED** [review]

**Comment by iosmanthus** [comment]
LGTM

**Review by iosmanthus — APPROVED** [review]
LGTM
