### PR TITLE
[to #462] add version constraint for rawkv tests

### LINKED ISSUE #462: master branch compatibility tracking issue
### 1. Describe the bug

[master](https://github.com/tikv/client-java/commit/704fb005510cfc3dcf161537b1640d6fd34e650a) branch is not fully compatible with an older version of TiKV. This issue is created for tracking the sub-issues of forwarding compatibility of the master branch of client-java.

|    |     failed tests      |
|----------|:-------------:|
| v5.0.x |  RegionSplitTest, RawKVIngestTest, PDClientIntegrationTest |
| v5.1.x | RawKVIngestTest, PDClientIntegrationTest |
| v5.2.0 | PDClientIntegrationTest |
| v5.3.0 | not tests |

### 2. Minimal reproduce step (Required)
Using `tiup playground` to deploy different versions of TiKV and run the client-java tests with `mvn test -Dtest=...`

### 3. What did you see instead (Required)
Some tests failed.

### 4. What did you expect to see? (Required)
All tests pass, incompatible tests should not run while the TiKV version is not matched.
### 5. What are your Java Client and TiKV versions? (Required)

- Client Java: https://github.com/tikv/client-java/commit/704fb005510cfc3dcf161537b1640d6fd34e650a
- TiKV: as mentioned above

### PR DESCRIPTION
**Pull request by iosmanthus**
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>

### What problem does this PR solve?

Issue Number: close #462

Problem Description:
Some tests in the master branch are not compatible with older versions of TiKV, we need to add some version constraints to these tests and furthermore, add integration compatibility tests for the master branch.

### What is changed and how it works?

Use `Assume` to ignore some tests with version info reading from ENV.

### Check List for Tests

This PR has been tested by at least one of the following methods:
- Manual test (add detailed scripts or steps below)

### CODE REVIEW

File: src/test/java/org/tikv/BaseRawKVTest.java [hunk 1]
```diff
@@ -21,6 +21,21 @@
 import org.tikv.util.TestUtils;
 
 public class BaseRawKVTest {
+
+  protected String getTiKVVersion() {
+    String tikvVersion = TestUtils.getEnv("TIKV_VERSION");
```
Comment (marsishandsome) [inline src/test/java/org/tikv/BaseRawKVTest.java:26]: Who will set the `TIKV_VERSION`?

Comment (marsishandsome) [reply src/test/java/org/tikv/BaseRawKVTest.java:26]: we can get the tikv version from TiKV, see https://github.com/tikv/client-java/blob/master/src/main/java/org/tikv/common/StoreVersion.java.

Comment (iosmanthus) [reply src/test/java/org/tikv/BaseRawKVTest.java:26]: Cool

Comment (iosmanthus) [reply src/test/java/org/tikv/BaseRawKVTest.java:26]: > Who will set the `TIKV_VERSION`?

By design, like RAWKV_PD_ADDRESSES, it will be set by the test excecutor.

**Review by marsishandsome — APPROVED** [review]
LGTM

**Review by zz-jason — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
